version: "1.0"
info:
  model: int-scaffold
packages:
- name: TestGitProject06Project
  gitServerName: SanthoshKToken7D
  gitUrl: https://github.com/santhu736852
  gitUsername: santhu736852
  gitBranch: main
services:
- serviceName: project.testgitproject06.integrations:testv
  packages:
  - name: TestGitProject06Project
    version: "1.0"
- serviceName: pub.date:getCurrentDate
  packages:
  - name: WmPublic
    version: 11.1.0.0.1120
